version: "2"
services:
  perfectworld-authd:
    container_name: perfectworld-authd
    depends_on:
      - perfectworld-uniquenamed
    expose:
      - "29200/tcp"
    restart: always
    environment:
      AUTHD_SERVER_ADDRESS: 0.0.0.0
      AUTHD_SERVER_PORT: 29200
      MYSQL_ADDRESS: 172.30.1.20
      MYSQL_PORT: 3306
      MYSQL_DB: pw
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    image: ossperfectworld/perfect-world-authd:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.4
  perfectworld-db:
    container_name: perfectworld-db
    image: mysql:5.7
    restart: always
    expose:
      - "3306/tcp"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - perfectworld-mysql-volume:/var/lib/mysql
    networks:
      infrastructure:
        ipv4_address: 172.30.1.20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pw
      MYSQL_USER: unused
      MYSQL_PASSWORD: unused
  perfectworld-gacd:
    container_name: perfectworld-gacd
    depends_on:
        - perfectworld-gamedbd
    expose:
      - "29702/tcp"
      - "29712/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      GACD_SERVER_ADDRESS: 0.0.0.0
      GACD_ANTICHEAT_SERVER_PORT: 29702
      GACD_CONTROL_SERVER_PORT: 29712
    image: ossperfectworld/perfect-world-gacd:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.6
  perfectworld-gamed:
    container_name: perfectworld-gamed
    depends_on:
        - perfectworld-glinkd
    restart: always
    environment:
      GDELIVERYD_SERVER_ADDRESS: 172.30.1.8
      GDELIVERYD_PROVIDER_SERVER_PORT: 29300
      GAMEDBD_SERVER_ADDRESS: 172.30.1.5
      GAMEDBD_SERVER_PORT: 29400
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      GFACTIOND_SERVER_ADDRESS: 172.30.1.7
      GPROVIDER_SERVER_PORT: 29600
      GLINKD_SERVER_ADDRESS: 172.30.1.9
      GLINKD_DELIVERY_SERVER_1_PORT: 29301
      GLINKD_DELIVERY_SERVER_2_PORT: 29302
      GLINKD_DELIVERY_SERVER_3_PORT: 29303
      GLINKD_DELIVERY_SERVER_4_PORT: 29304
      GLINKD_DELIVERY_SERVER_5_PORT: 29305
      GLINKD_DELIVERY_SERVER_6_PORT: 29306
      GLINKD_DELIVERY_SERVER_7_PORT: 29307
    image: ossperfectworld/perfect-world-gamed:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.10
  perfectworld-gamedbd:
    container_name: perfectworld-gamedbd
    depends_on:
        - perfectworld-authd
    expose:
      - "29400/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      GAMEDBD_SERVER_ADDRESS: 0.0.0.0
      GAMEDBD_SERVER_PORT: 29400
    image: ossperfectworld/perfect-world-gamedbd:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.5
  perfectworld-gdeliveryd:
    container_name: perfectworld-gdeliveryd
    depends_on:
        - perfectworld-gfactiond
    expose:
      - "29300/tcp"
      - "29100/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      AUTHD_SERVER_ADDRESS: 172.30.1.4
      AUTHD_SERVER_PORT: 29200
      UNIQUENAMED_SERVER_ADDRESS: 172.30.1.3
      UNIQUENAMED_SERVER_PORT: 29401
      GAMEDBD_SERVER_ADDRESS: 172.30.1.5
      GAMEDBD_SERVER_PORT: 29400
      GACD_SERVER_ADDRESS: 172.30.1.6
      GACD_ANTICHEAT_SERVER_PORT: 29702
      GFACTIOND_SERVER_ADDRESS: 172.30.1.7
      GFACTION_SERVER_PORT: 29500
      GDELIVERYD_SERVER_ADDRESS: 0.0.0.0
      GDELIVERYD_PROVIDER_SERVER_PORT: 29300
      GDELIVERYD_SERVER_PORT: 29100
    image: ossperfectworld/perfect-world-gdeliveryd:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.8
  perfectworld-gfactiond:
    container_name: perfectworld-gfactiond
    depends_on:
        - perfectworld-gacd
    expose:
      - "29500/tcp"
      - "29600/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      GFACTIOND_SERVER_ADDRESS: 0.0.0.0
      GFACTION_SERVER_PORT: 29500
      GPROVIDER_SERVER_PORT: 29600
      GAMEDBD_SERVER_ADDRESS: 172.30.1.5
      GAMEDBD_SERVER_PORT: 29400
      UNIQUENAMED_SERVER_ADDRESS: 172.30.1.3
      UNIQUENAMED_SERVER_PORT: 29401
    image: ossperfectworld/perfect-world-gfactiond:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.7
  perfectworld-glinkd:
    container_name: perfectworld-glinkd
    depends_on:
        - perfectworld-gdeliveryd
    ports:
    - "{PUBLIC_IP}:29000:29000"
    expose:
      - "29000/tcp"
      - "29001/tcp"
      - "29002/tcp"
      - "29003/tcp"
      - "29004/tcp"
      - "29005/tcp"
      - "29006/tcp"
      - "29301/tcp"
      - "29302/tcp"
      - "29303/tcp"
      - "29304/tcp"
      - "29305/tcp"
      - "29306/tcp"
      - "29307/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      GFACTIOND_SERVER_ADDRESS: 172.30.1.7
      GFACTION_SERVER_PORT: 29500
      GDELIVERYD_SERVER_ADDRESS: 172.30.1.8
      GDELIVERYD_SERVER_PORT: 29100
      GLINKD_SERVER_ADDRESS: 0.0.0.0
      GLINKD_SERVER_1_PORT: 29000
      GLINKD_SERVER_2_PORT: 29001
      GLINKD_SERVER_3_PORT: 29002
      GLINKD_SERVER_4_PORT: 29003
      GLINKD_SERVER_5_PORT: 29004
      GLINKD_SERVER_6_PORT: 29005
      GLINKD_SERVER_7_PORT: 29006
      GLINKD_DELIVERY_SERVER_1_PORT: 29301
      GLINKD_DELIVERY_SERVER_2_PORT: 29302
      GLINKD_DELIVERY_SERVER_3_PORT: 29303
      GLINKD_DELIVERY_SERVER_4_PORT: 29304
      GLINKD_DELIVERY_SERVER_5_PORT: 29305
      GLINKD_DELIVERY_SERVER_6_PORT: 29306
      GLINKD_DELIVERY_SERVER_7_PORT: 29307
    image: ossperfectworld/perfect-world-glinkd:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.9
  perfectworld-logservice:
    container_name: perfectworld-logservice
    depends_on:
        - perfectworld-db
    expose:
      - "11100/udp"
      - "11101/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 0.0.0.0
    image: ossperfectworld/perfect-world-logservice:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.2
  perfectworld-uniquenamed:
    container_name: perfectworld-uniquenamed
    depends_on:
        - perfectworld-logservice
    expose:
      - "29401/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 172.30.1.2
      UNIQUENAMED_SERVER_ADDRESS: 0.0.0.0
      UNIQUENAMED_SERVER_PORT: 29401
    image: ossperfectworld/perfect-world-uniquenamed:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.3
  perfectworld-website-register:
    container_name: perfectworld-website-register
    ports:
    - "{PUBLIC_IP}:80:80"
    expose:
      - "80/tcp"
    environment:
      MYSQL_ADDRESS: 172.30.1.20
      MYSQL_DB: pw
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      USER_GOLD: 1000000
    image: ossperfectworld/perfect-world-website-register:latest
    networks:
      infrastructure:
        ipv4_address: 172.30.1.30

volumes:
  perfectworld-mysql-volume:

networks:
  infrastructure:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
         gateway: 172.30.0.1
